### ISSUE TITLE
Move .coveragerc into pyproject.toml

### ISSUE THREAD

**Issue by brettcannon** [jaraco/skeleton#14]
Might as well cut out a file. 😄 

https://coverage.readthedocs.io/en/coverage-5.0.4/config.html

**Comment by jaraco** [comment]
Hmm. I've historically let each tool prefer its own file, in part because it serves as a signal to someone inspecting the project that the tool is used, but also to provide for separation of concerns. It's also the only approach that I'm able to apply consistently. For example, pytest allows use of pytest.ini, tox.ini, or setup.cfg. flake8 honors some files like setup.cfg and pyproject.toml. Chosing the project's preferred config file seems like the best approach to apply consistently. It seems to me a fool's errand to arbitrarily choose one over another, especially piecemeal. How about we defer this tweak until there's documented guidance or consensus that pyproject.toml is the preferred file for all config for all tools, and then do it with all the tools that support it?

**Comment by brettcannon** [comment]
Flake8 actually [doesn't use pyproject.toml](https://gitlab.com/pycqa/flake8/-/issues/428#note_251982786).

And fair enough! I don't think you will ever get documented guidance but possibly consensus.

**Comment by jaraco** [comment]
I should say too, I'm happy for `skeleton` and its derivative projects to be helping drive the consensus and not just following. I just want to avoid making capricious changes.
