### ISSUE TITLE
Bump pytest-mypy

### ISSUE THREAD

**Issue by Avasam** [jaraco/skeleton#96]
No particular reason or blocker, other than updating (new checks, bugfixes, etc.) relevant tooling for https://github.com/pypa/setuptools/pull/3979#discussion_r1367961634

Latest version as of writing this was https://pypi.org/project/pytest-mypy/0.10.3/ nearly a year ago.

**Comment by jaraco** [comment]
I generally don't bump the minumum requirements unless there's a specific reason to do so. It ends up being a lot of toil for little benefit, since most systems will just pick up the latest version anyway. What do you think about dropping the minimum requirement, since I don't even recall why it's there?

**Comment by Avasam** [comment]
Makes sense to me to just drop it. Unless we find a specific recent mypy feature, or stdlib typeshed stub, that is needed.

And as you said, it's more trouble to go look for it now than just dropping the min version requirement
